name: Build TWRP Final
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preparation
        run: |
          sudo apt update
          sudo apt install gperf gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses6 lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc python3 -y

      - name: Install Repo and Sync Source
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH=~/bin:$PATH
          mkdir twrp && cd twrp
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -j$(nproc --all)

      - name: Build Recovery
        run: |
          export PATH=~/bin:$PATH
          mkdir -p twrp/device/tecno/KL5
          # نسخ ملفات الإعدادات من المستودع إلى بيئة البناء
          find . -maxdepth 1 -not -name 'twrp' -not -name '.' -exec cp -r {} twrp/device/tecno/KL5/ \;
          cd twrp
          source build/envsetup.sh
          lunch twrp_KL5-eng
          
          # تجاوز أخطاء فقدان الوحدات (حل مشكلة الصورة 1000000775.jpg)
          export ALLOW_MISSING_DEPENDENCIES=true
          mka recoveryimage -j$(nproc --all)

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: TWRP-KL5-Final-Image
          # هذا المسار سيبحث في كل المجلدات الناتجة عن البناء دون استثناء
          path: |
            twrp/out/target/product/*/recovery.img
            twrp/out/target/product/*/*.zip
          if-no-files-found: error
